export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "https://images.pexels.com/photos/7532110/pexels-photo-7532110.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "https://images.pexels.com/photos/11295165/pexels-photo-11295165.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: "https://images.pexels.com/photos/4371669/pexels-photo-4371669.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "https://images.pexels.com/photos/7608079/pexels-photo-7608079.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "https://images.pexels.com/photos/13388047/pexels-photo-13388047.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "https://images.pexels.com/photos/11378899/pexels-photo-11378899.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "https://images.pexels.com/photos/4820241/pexels-photo-4820241.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
  },
];

export const projects = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Packaging Design",
    username: "Freddie Johnston",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Social Media Design",
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Illustration",
    username: "Dalton Hudson",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Book Design",
    username: "Hannah Dougherty",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Digital Marketing",
    username: "Ward Brewer",
  },
];

export const countries = {
  ad: "andorra",
  ae: "united arab emirates",
  af: "afghanistan",
  ag: "antigua and barbuda",
  ai: "anguilla",
  al: "albania",
  am: "armenia",
  ao: "angola",
  aq: "antarctica",
  ar: "argentina",
  as: "american samoa",
  at: "austria",
  au: "australia",
  aw: "aruba",
  ax: "åland islands",
  az: "azerbaijan",
  ba: "bosnia and herzegovina",
  bb: "barbados",
  bd: "bangladesh",
  be: "belgium",
  bf: "burkina faso",
  bg: "bulgaria",
  bh: "bahrain",
  bi: "burundi",
  bj: "benin",
  bl: "saint barthélemy",
  bm: "bermuda",
  bn: "brunei",
  bo: "bolivia",
  bq: "caribbean netherlands",
  br: "brazil",
  bs: "bahamas",
  bt: "bhutan",
  bv: "bouvet island",
  bw: "botswana",
  by: "belarus",
  bz: "belize",
  ca: "canada",
  cc: "cocos (keeling) islands",
  cd: "dr congo",
  cf: "central african republic",
  cg: "republic of the congo",
  ch: "switzerland",
  ci: "côte d'ivoire (ivory coast)",
  ck: "cook islands",
  cl: "chile",
  cm: "cameroon",
  cn: "china",
  co: "colombia",
  cr: "costa rica",
  cu: "cuba",
  cv: "cape verde",
  cw: "curaçao",
  cx: "christmas island",
  cy: "cyprus",
  cz: "czechia",
  de: "germany",
  dj: "djibouti",
  dk: "denmark",
  dm: "dominica",
  do: "dominican republic",
  dz: "algeria",
  ec: "ecuador",
  ee: "estonia",
  eg: "egypt",
  eh: "western sahara",
  er: "eritrea",
  es: "spain",
  et: "ethiopia",
  eu: "european union",
  fi: "finland",
  fj: "fiji",
  fk: "falkland islands",
  fm: "micronesia",
  fo: "faroe islands",
  fr: "france",
  ga: "gabon",
  gb: "united kingdom",
  gd: "grenada",
  ge: "georgia",
  gf: "french guiana",
  gg: "guernsey",
  gh: "ghana",
  gi: "gibraltar",
  gl: "greenland",
  gm: "gambia",
  gn: "guinea",
  gp: "guadeloupe",
  gq: "equatorial guinea",
  gr: "greece",
  gs: "south georgia",
  gt: "guatemala",
  gu: "guam",
  gw: "guinea-bissau",
  gy: "guyana",
  hk: "hong kong",
  hm: "heard island and mcdonald islands",
  hn: "honduras",
  hr: "croatia",
  ht: "haiti",
  hu: "hungary",
  id: "indonesia",
  ie: "ireland",
  il: "israel",
  im: "isle of man",
  in: "india",
  io: "british indian ocean territory",
  iq: "iraq",
  ir: "iran",
  is: "iceland",
  it: "italy",
  je: "jersey",
  jm: "jamaica",
  jo: "jordan",
  jp: "japan",
  ke: "kenya",
  kg: "kyrgyzstan",
  kh: "cambodia",
  ki: "kiribati",
  km: "comoros",
  kn: "saint kitts and nevis",
  kp: "north korea",
  kr: "south korea",
  kw: "kuwait",
  ky: "cayman islands",
  kz: "kazakhstan",
  la: "laos",
  lb: "lebanon",
  lc: "saint lucia",
  li: "liechtenstein",
  lk: "sri lanka",
  lr: "liberia",
  ls: "lesotho",
  lt: "lithuania",
  lu: "luxembourg",
  lv: "latvia",
  ly: "libya",
  ma: "morocco",
  mc: "monaco",
  md: "moldova",
  me: "montenegro",
  mf: "saint martin",
  mg: "madagascar",
  mh: "marshall islands",
  mk: "north macedonia",
  ml: "mali",
  mm: "myanmar",
  mn: "mongolia",
  mo: "macau",
  mp: "northern mariana islands",
  mq: "martinique",
  mr: "mauritania",
  ms: "montserrat",
  mt: "malta",
  mu: "mauritius",
  mv: "maldives",
  mw: "malawi",
  mx: "mexico",
  my: "malaysia",
  mz: "mozambique",
  na: "namibia",
  nc: "new caledonia",
  ne: "niger",
  nf: "norfolk island",
  ng: "nigeria",
  ni: "nicaragua",
  nl: "netherlands",
  no: "norway",
  np: "nepal",
  nr: "nauru",
  nu: "niue",
  nz: "new zealand",
  om: "oman",
  pa: "panama",
  pe: "peru",
  pf: "french polynesia",
  pg: "papua new guinea",
  ph: "philippines",
  pk: "pakistan",
  pl: "poland",
  pm: "saint pierre and miquelon",
  pn: "pitcairn islands",
  pr: "puerto rico",
  ps: "palestine",
  pt: "portugal",
  pw: "palau",
  py: "paraguay",
  qa: "qatar",
  re: "réunion",
  ro: "romania",
  rs: "serbia",
  ru: "russia",
  rw: "rwanda",
  sa: "saudi arabia",
  sb: "solomon islands",
  sc: "seychelles",
  sd: "sudan",
  se: "sweden",
  sg: "singapore",
  sh: "saint helena, ascension and tristan da cunha",
  si: "slovenia",
  sj: "svalbard and jan mayen",
  sk: "slovakia",
  sl: "sierra leone",
  sm: "san marino",
  sn: "senegal",
  so: "somalia",
  sr: "suriname",
  ss: "south sudan",
  st: "são tomé and príncipe",
  sv: "el salvador",
  sx: "sint maarten",
  sy: "syria",
  sz: "eswatini (swaziland)",
  tc: "turks and caicos islands",
  td: "chad",
  tf: "french southern and antarctic lands",
  tg: "togo",
  th: "thailand",
  tj: "tajikistan",
  tk: "tokelau",
  tl: "timor-leste",
  tm: "turkmenistan",
  tn: "tunisia",
  to: "tonga",
  tr: "turkey",
  tt: "trinidad and tobago",
  tv: "tuvalu",
  tw: "taiwan",
  tz: "tanzania",
  ua: "ukraine",
  ug: "uganda",
  um: "united states minor outlying islands",
  un: "united nations",
  us: "united states",
  uy: "uruguay",
  uz: "uzbekistan",
  va: "vatican city (holy see)",
  vc: "saint vincent and the grenadines",
  ve: "venezuela",
  vg: "british virgin islands",
  vi: "united states virgin islands",
  vn: "vietnam",
  vu: "vanuatu",
  wf: "wallis and futuna",
  ws: "samoa",
  xk: "kosovo",
  ye: "yemen",
  yt: "mayotte",
  za: "south africa",
  zm: "zambia",
  zw: "zimbabwe",
};
